version: "3.9"

services:
  # --- SEUS SERVIÇOS ATUAIS ---
  api:
    build: .
    container_name: api_node
    ports:
      - "5001:5001"
    environment:
      # A sua API vai se conectar no FerretDB usando este endereço interno:
      - MONGO_URL=mongodb://ferretdb:27017/meu_banco
    depends_on:
      - ferretdb

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  # --- NOVOS SERVIÇOS (FERRETDB + POSTGRES) ---
  postgres:
    image: postgres:16
    container_name: ferretdb-postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ferretdb
    ports:
      - "5432:5432" # Opcional: só se você quiser olhar o Postgres por fora
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:latest
    container_name: ferretdb
    restart: always
    ports:
      - "27017:27017" # Expõe a porta do Mongo para você conectar via Compass no seu PC
    environment:
      FERRETDB_POSTGRESQL_URL: "postgres://username:password@postgres:5432/ferretdb"
    depends_on:
      - postgres

volumes:
  grafana_data:
  postgres_data: # Volume adicionado para persistir os dados do Postgres